додав утіліти, брейкпоінти, кольора і комон
IrynaSokolova-Quanandrya/super-7-team-proj pull request #2
Opened 2022-08-27 15:51 UTC by HECKONCHIK

додав утіліти, брейкпоінти, кольора і комон

2022-08-27 19:37 UTC, IrynaSokolova-Quanandrya requested changes

2022-08-27 19:37 UTC, IrynaSokolova-Quanandrya commented on src/sass/index.scss
> +@import './veriables/brekpoints';
breakpoints - виправ слово)

2022-08-27 19:37 UTC, IrynaSokolova-Quanandrya commented on src/sass/_common.scss
>  @import '~node_modules/modern-normalize/modern-normalize.css';
Що це за імпорт?

2022-08-27 19:37 UTC, IrynaSokolova-Quanandrya commented on src/sass/veriables/_veriables.scss
> +:root {
давай будемо використовувати sass змінні типу $blablabla

2022-08-28 11:04 UTC, HECKONCHIK commented on src/sass/_common.scss
>  @import '~node_modules/modern-normalize/modern-normalize.css';
він там був з самого початку

2022-08-28 11:05 UTC, HECKONCHIK commented on src/sass/veriables/_veriables.scss
> +:root {
ок

2022-08-28 12:32 UTC, merged